name: glance

services:
  glance:
    container_name: ${service_name}_app
    image: glanceapp/glance
    restart: always
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    # ports:
    #   - 8080:8080
    env_file: .env
    depends_on:
      - tailscale
    network_mode: "service:tailscale"

  tailscale:
    image: tailscale/tailscale:stable
    container_name: ${service_name}_tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=${service_name}
    volumes:
      - ${PWD}/${service_name}_tailscale/state:/var/lib/tailscale
      - ./tailscale.json:/config/tailscale.json
      - /dev/net/tun:/dev/net/tun
    # cap_drop:
    #  - ALL
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online.*true'
    deploy:
      resources:
        limits:
          pids: 100